### PR TITLE
Fixed all issues listed

### PR DESCRIPTION
**Pull request by Jakeclearwater**
Added more comments for readability and changed a variable so it worked

### CODE REVIEW

**Review by schekt1 — APPROVED** [review]
Looks good, happy for you to go ahead and merge these changes.

**Review by ghost — APPROVED** [review]
Looks good

**Comment by Jakeclearwater** [comment]
Commited a few more issues that have been fixed, please re-review my merge request :)

**Review by aardhyn — APPROVED** [review]
great formatting and commenting! good to merge

**Pull request merged**
